name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inscriptions_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.7.2
      - name: Install bundler
        run: gem install bundler
      - name: Setup PG
        run: sudo apt-get -yqq install libpq-dev
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install Gems
        run: |
          bundle config path vendor/bundle
          bin/bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Run unit tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/inscriptions_test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RACK_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails test
